export enum types {
    ADD_TO_CART = 'ADD_TO_CART',
    CHANGE_CART_PRODUCTS_COUNT = 'CHANGE_CART_PRODUCTS_COUNT',
    INCRIMENT_CART_PRODUCT_COUNT = 'INCRIMENT_CART_PRODUCT_COUNT',
    DECRIMENT_CART_PRODUCT_COUNT = 'DECRIMENT_CART_PRODUCT_COUNT',
    DELETE_CART_PRODUCT = 'DELETE_CART_PRODUCT',
    CLEAR_CART_PRODUCTS = 'CLEAR_CART_PRODUCTS'

}